
export const Tasks = [
    { 
        id: 1,
        description: "1 Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        category: "Health",
        frequency: "Daily",
        hour: 7,
        minute: 5,
        day: 1,
        month: 7,
        year: 2022,
        isCompleted: false,
    },
    { 
        id: 2,
        description: "2 Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        category: "Work",
        frequency: "Daily",
        hour: 12,
        minute: 30,
        day: 2,
        month: 7,
        year: 2022,
        isCompleted: true,
    },
    { 
        id: 3,
        description: "3 Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        category: "Home",
        frequency: "Weekly",
        hour: 9,
        minute: 45,
        day: 5,
        month: 7,
        year: 2022,
        isCompleted: false,
    },
    { 
        id: 4,
        description: "4 Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        category: "Family",
        frequency: "Monthly",
        hour: 17,
        minute: 10,
        day: 7,
        month: 9,
        year: 2022,
        isCompleted: false,
    },
    { 
        id: 5,
        description: "5 Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        category: "Health",
        frequency: "Daily",
        hour: 11,
        minute: 20,
        day: 6,
        month: 7,
        year: 2022,
        isCompleted: false,
    },
    { 
        id: 6,
        description: "6 Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        category: "Work",
        frequency: "Weekly",
        hour: 13,
        minute: 30,
        day: 3,
        month: 8,
        year: 2022,
        isCompleted: false,
    },
    { 
        id: 7,
        description: "7 Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        category: "Home",
        frequency: "Monthly",
        hour: 20,
        minute: 0,
        day: 5,
        month: 7,
        year: 2022,
        isCompleted: false,
    },
];

export const User = {
    name: "John Doe",
    email: "johndoe01@gmail.com",
    password: "", 
};
